steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/cloud-lab-497409/cloud-lab-repo/cloud-lab:$COMMIT_SHA
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/cloud-lab-497409/cloud-lab-repo/cloud-lab:$COMMIT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - cloud-lab
      - --image=us-central1-docker.pkg.dev/cloud-lab-497409/cloud-lab-repo/cloud-lab:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=5000

images:
  - us-central1-docker.pkg.dev/cloud-lab-497409/cloud-lab-repo/cloud-lab:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY